services:
  api:
    container_name: taskmanager
    image: taskmanager-api:latest
    ports:
      - '49160:${PORT}'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - taskmanager-net
    restart: unless-stopped

  postgres:
    container_name: taskmanager-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 5436:5432
    volumes:
      - tasksys-data:/var/lib/postgresql/data
    networks:
      - taskmanager-net

volumes:
  tasksys-data:


networks:
  taskmanager-net:
    driver: bridge
